version: 0.0
os: linux 
files:
  - source: /
    destination: /root/plus-util-front 
    overwrite: yes
permissions: 
  - object: /root/plus-util-front
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall: 
    - location: deploy.sh 
      timeout: 100 
      runas: root